import Head from "next/head";
import Header from "@/components/Shared/Header";
import Footer from "@/components/Shared/Footer";
import PageWrapper from "@/components/Shared/PageWrapper";

export default function Layout({ children, title = "Alnafaz" }) {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="sticky top-0 bg-white z-50">
        <Header />
      </header>
      <PageWrapper>
        {children}

        <Footer />
      </PageWrapper>
    </div>
  );
}
